### ISSUE TITLE
Dispatching does not pass through system level exceptions

### ISSUE THREAD

**Issue by RonnyPfannschmidt** [python-effect/effect#66]
SystemExit and KeyboardInterupt somehow managed to cause me a foldError

**Comment by radix** [comment]
I'll have to keep thinking about this.

First off: I know it sucks. I'm sorry.

One thing is that if we don't catch KeyboardInterrupt in Effect, it means you can't "naturally" handle KeyboardInterrupt in Effect-using code the same way that you can "naturally" handle KeyboardInterrupt in a regular Python program. That is, you'd never be able to do `.on(error=catch(KeyboardInterrupt, ...))`, since KeyboardInterrupt would never be propagated. It's useful to be able to do this to write interactive programs, since you may want to handle any exception -- even KeyboardInterrupt -- to clean up some resources before exiting.

I think SystemExit, on the other hand, is probably pretty safe to never catch. I don't think I've ever seen a sane use of `except SystemExit`.

_another_ thing that I'm reconsidering is the default behavior of having `fold_effects` and `parallel` raise FoldError and FirstError. I think it's important to be able to offer this functionality so people know when in the process of folding an exception happened, or which parallel effect caused an error, but I don't think they want it most of the time (or if they do, it's only to log it; then just propagate/handle the underlying exception).

So, if I solve the second problem (by making it possible for fold_effect to not wrap errors), then in _some_ cases KeyboardInterrupt will be propagated. The constraints are: 1) you're using `sync_perform`, and 2) you don't have any "bare" error handlers, that, say, catch and log all exceptions regardless of their type.

Admittedly it is probably pretty common to have bare error handlers, so that may not be enough.

I'd also love to be able to have a way to "annotate" exceptions without wrapping them. It's a problem I seen in lots of different Python codebases. If I could somehow annotate any exception raised through a fold_effect to add information about where the fold error happened, without changing its type, then we wouldn't have this problem. Of course I can't rely on just setting attributes on the object (not only would that be hacky and perhaps stomp on existing attributes, it's simply not possible given that some exceptions could not allow attribute-assignment). My mind wanders to other solutions for this, but they're all really horrible and error-prone.

**Comment by RonnyPfannschmidt** [comment]
How about providing such handlers as library opt in? And adding a bare fold/sequence that does not apply the handlers?

**Comment by radix** [comment]
Effect and txeffect now no longer have any bare `except:`s, so this should no longer be a problem.
