### ISSUE TITLE
do_return needed on all Python versions

### ISSUE THREAD

**Issue by rbtcollins** [python-effect/effect#71]
the docstrings claim its not needed on Python3. But it certainly appears to be so.

```
>>> import effect
f>>> from effect.do import do
>>> from effect.testing import perform_sequence
>>> @do
... def t():
...   yield 5
... 
>>> perform_sequence([], t())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/robertc/work/effect/effect/testing.py", line 107, in perform_sequence
    return sync_perform(dispatcher, eff)
  File "/home/robertc/work/effect/effect/_sync.py", line 34, in sync_perform
    six.reraise(*errors[0])
  File "/home/robertc/.virtualenvs/effect-3.5/lib/python3.5/site-packages/six.py", line 659, in reraise
    raise value
  File "/home/robertc/work/effect/effect/_sync.py", line 72, in sync_wrapper
    box.succeed(f(*pass_args, **kwargs))
  File "/home/robertc/work/effect/effect/_intents.py", line 181, in perform_func
    return intent.func()
  File "/home/robertc/work/effect/effect/do.py", line 64, in doit
    return _do(None, gen, False)
  File "/home/robertc/work/effect/effect/do.py", line 125, in _do
    "Got %r from %r" % (val, generator))
TypeError: @do functions must only yield Effects or results of do_return. Got 5 from <generator object t at 0x7fb11094bb48>
>>> import sys
>>> sys.version_info
sys.version_info(major=3, minor=5, micro=0, releaselevel='candidate', serial=1)
```

**Comment by radix** [comment]
I'm kind of confused by what you're expecting. On Python 3, you can use `return` normally to specify the final return value. On Python 2, to specify the final return value, you must use `yield do_return`. Your example does neither, and is just `yield`ing a plain value. You can only yield Effects or the result of `do_return`.

**Comment by radix** [comment]
Closing this. If you think there's still a bug please feel free to reopen.

**Comment by rbtcollins** [comment]
github won't let me reopen it. The pasted code block demonstrated using python 3 with a plain return and it failing.

**Comment by rbtcollins** [comment]
Oh - I think I get it. The docs are horribly unclear. At minimum this is a doc bug. But I think we could just make yielding final values work, no?

**Comment by radix** [comment]
@rbtcollins can you be more specific about what's unclear? let me quote the relevant part of the docstring:


> Any yielded values must either be Effects or the result of a :func:`do_return` call. The result of a yielded Effect will be passed back into the generator as the result of the ``yield`` expression. Yielded :func:`do_return` values will provide the ultimate result of the Effect that is returned by the decorated function. Note that :func:`do_return` is only necessary for Python 2 compatibility; return statements can be used directly in Python 3-only code.

I don't see anything inaccurate or incomplete about that docstring, but I may be missing something. Did you perhaps misread `return` as `yield`? Perhaps the docstring could be improved, but I'm not sure if there's a "bug" (in the sense that something is actually incorrect). If you have any suggestions (or a PR) I would be happy to accept them :)

As for your question about making `yield` work, I decided against that because I thought the more explicit API was preferable. For example, what would you expect the following to do?

```python
@do
def foo():
    yield 1
    yield 2
```

`do_return` specifically *stops* the generator and specifies the return value. This allows constructs like this:

```python
@do
def foo():
    if x:
        yield do_return(x + 1)
    else:
        yield do_return('blah')
```

This makes it more similar to a plain `return` statement.

If you use plain non-Effect values as return values, should it stop the generator?  I specifically avoided this unclear API design issue by making returning explicit.

**Comment by rbtcollins** [comment]
Yes, I think its the slight ambiguity between 'return x' and 'yield x' just didn't click when I read the prose. Code examples would be clearer I think.

do_return only stops the generator because its a marker interface. Its no more or less deterministic.

Yes, I think 
```
@do
def foo():
    yield 1
    yield 2
```

should be the moral equivalent of
```
def foo():
    return 1
    return 2
```

in a non-do function.

**Comment by tomprince** [comment]
That isn't the only possible interpretation (and not the one that somebody used to twisted's `inlinceCallbacks` would expect).

```
@do
def foo():
    assert 2 == (yield 2)
```

Given the multiple possible interpretations, I think not supporting any of them (given that all the possibilities are still expressible) is the best course.

**Comment by radix** [comment]
Thanks for the input @tomprince 

Yeah, I am still inclined towards the explicit return API being better than allowing yielding arbitrary values.

**Comment by rbtcollins** [comment]
Its your call of course, but Python2 is with us for at least another 5 years (and if 2.6 is any guide, 10). do_return doesn't add any capabilities.

```
assert 2 == (yield do_return(2))
```

**Comment by radix** [comment]
My argument isn't that `do_return` adds any *functionality*. I just prefer its explicitness. I'm not sure what your `assert` snippet is meant to express...

**Comment by rbtcollins** [comment]
Just to show that its as syntactically valid - and will equally fail to actually assess the assertion.

**Comment by tomprince** [comment]
@rbtcollins I guess I wasn't explicit enough. In twisted's equivalent of `do`, if you yield something that isn't a `Deferred` (the equivalent of an `Effect`), that value is just sent back into the generator. That means that the `yield` is essentially a no-op if you yield something that isn't marked.
So the assert is basically `assert 2 == 2` in the snipped I had.

**Comment by rbtcollins** [comment]
Sure. But inlinecallbacks isn't do - its twisted thing from way back - if python-effect were to be identical to deferred's, there'd be little point in it, no?

**Comment by rbtcollins** [comment]
And idea from https://trollius.readthedocs.org/asyncio.html - use raise rather than yield. That avoids the confusing fact that you can yield do_return(thing1);yield do_return(thing2)

**Comment by radix** [comment]
@rbtcollins `@do` is already implemented such that `yield do_return(thing1)` stops the function. I specifically avoided the `raise` solution because it makes returning inside of a try/except block very awkward. (fwiw `@inlineCallbacks` also uses an exception-based solution, and it informed my decision to *not* use exceptions :))

**Comment by radix** [comment]
I've actually been thinking of a completely different application for bare yields: to treat them as intents (without the Effect wrapper). This would clean up a significant amount of boilerplate...


```python
@do
def greet_eff():
    name = yield Effect(Prompt('Enter your name> '))
    greeting = 'Why hello there, %s!' % (name,)
    yield Effect(Display(greeting))
    friend_name = yield Effect(Prompt("And what is your friend's name? "))
    yield Effect(Display("It's good to meet you too, %s." % (friend_name,)))
```

vs

```python
@do
def greet_eff():
    name = yield Prompt('Enter your name> ')
    greeting = 'Why hello there, %s!' % (name,)
    yield Display(greeting)
    friend_name = yield Prompt("And what is your friend's name? ")
    yield Display("It's good to meet you too, %s." % (friend_name,))
```

But it's just a thought, I'm not sure I want to do this since it complicates the interface (we'd absolutely need to continue to support Effects as well as intents).

**Comment by rbtcollins** [comment]
I see the issue with try + *bare* except, but any scoped except should be super unlikely to catch BaseException, FWIW.

So I like that removal of noise.

Seems we could have all of these at once:
yield Effect
yield bare thing -> wrap it in Effect
yield do_return(thing) -> an actual result
raise do_return(thing) -> an actual result

**Comment by radix** [comment]
I've deprecated do_return. Effect is now Python3-only, so we only use `return`.
